# Generated by Django 4.1.3 on 2022-11-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_island', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('categories', models.ManyToManyField(to='new_island.categories')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
