# Generated by Django 4.1.3 on 2022-11-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_island', '0002_articles_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='categories',
            field=models.ManyToManyField(blank=True, to='new_island.categories'),
        ),
    ]
