# Generated by Django 4.1.3 on 2022-11-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_island', '0003_alter_articles_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
