# Generated by Django 4.1.3 on 2022-11-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_island', '0004_articles_date_created_articles_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
