# Generated by Django 4.1.3 on 2022-11-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_island', '0005_alter_articles_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
